// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/binding/form": {
            "post": {
                "description": "FORM binding model.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "form binding sample for request info",
                "parameters": [
                    {
                        "description": "user password nick age",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.User"
                        }
                    }
                }
            }
        },
        "/binding/json": {
            "post": {
                "description": "JSON binding model.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "json binding sample for request info",
                "parameters": [
                    {
                        "description": "user password nick age",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.User"
                        }
                    }
                }
            }
        },
        "/binding/shouldbindquery": {
            "get": {
                "description": "querystring binding model.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "querystring binding sample for request info",
                "parameters": [
                    {
                        "description": "user password birthday",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/apis.UseMan"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.UseMan"
                        }
                    }
                }
            }
        },
        "/welcome/{name}": {
            "get": {
                "description": "자세한 설명은 이곳에 적습니다.\n자세한 설명은 이곳에 적습니다. - 2",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Summary를 적어 줍니다.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/apis.welcomeModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apis.UseMan": {
            "type": "object",
            "required": [
                "password",
                "user"
            ],
            "properties": {
                "birthday": {
                    "type": "string",
                    "format": "time.Time"
                },
                "password": {
                    "type": "string",
                    "format": "string"
                },
                "user": {
                    "type": "string",
                    "format": "string"
                }
            }
        },
        "apis.User": {
            "type": "object",
            "required": [
                "age",
                "password",
                "user"
            ],
            "properties": {
                "age": {
                    "type": "integer",
                    "format": "uint16",
                    "example": 46
                },
                "nick": {
                    "type": "string",
                    "format": "string",
                    "example": "nickname"
                },
                "password": {
                    "type": "string",
                    "format": "string"
                },
                "user": {
                    "type": "string",
                    "format": "string"
                }
            }
        },
        "apis.welcomeModel": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "account name"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Swagger Example API",
	Description: "This is a sample server Petstore server.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
